services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: edu_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: edu_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app_network

  bot:
    build: .
    depends_on:
      - db
      - vless-proxy
    command: >
      sh -c "
        python wait_db.py &&
        aerich init-db || aerich upgrade &&
        python main.py
      "
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DB_HOST: db
      DB_USER: edu_user
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: edu_manager
      PGPASSWORD: ${POSTGRES_PASSWORD}
      TZ: Etc/UTC
      HTTP_PROXY: "http://vless-proxy:8080"
      HTTPS_PROXY: "http://vless-proxy:8080"
    volumes:
      - ./appsettings.yaml:/app/appsettings.yaml
    restart: unless-stopped
    networks:
      - app_network

  vless-proxy:
    build: https://github.com/thejohnd0e/VLESS-to-HTTP.git
    container_name: vless-proxy
    restart: unless-stopped
    environment:
      - VLESS_URL=${VLESS_URL}
    command: >
      sh -c "
        echo '${VLESS_URL}' > /app/vless.conf &&
        /app/entrypoint.sh
      "
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: